functional:
Пользователь должен иметь возможность искать товары по ключевому слову
Пользователь должен иметь возможность искать товары по категории
Пользователь должен иметь возможность фильтровать товары
Пользователь должен иметь возможность просматривать товары 
Пользователь должен иметь возможность росматривать подробную информацию о товаре
Пользователь должен иметь возможность добавлять товары в корзину 
Пользователь должен иметь возможность просматривать содержимое корзины

non-functional:
Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
Сайт должен быть безопасным и защищать данные пользователя
Сайт должен иметь мобильную версию
Сайт нужно протестировать на совместимость с последними версиями браузеров
Важно, чтобы сайт мог обрабатывать большое количество трафика
Сайт должен быть доступен на различных устройствах

implicit:
Сайт должен иметь привлекательный внешний вид и удобный интерфейс
Сайт должен работать через HTTPS протокол
На сайте должна быть реализована возможность связи с поддержкой

