functional:
- Пользователь должен иметь возможность искать товары по ключевому слову 
- Пользователь должен иметь возможность искать товары по категории
- Пользователь должен иметь возможность фильтровать по производителю
- Пользователь должен иметь возможность фильтровать по цене
- Пользователь должен иметь возможность фильтровальтровать товар по наличию
- Пользователь должен иметь возможность просматривать товары 
- Пользователь должен иметь возможность просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину 
- Пользователь должен иметь возможность просматривать товары в корзине
- В карточке товара пользователь должен иметь возможность просматривать фотографии в крупном плане
- В корзине пользователь должен иметь возможность увеличивать и уменьшать колличество каждого добавленного товара
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
implicit (usability):
- Описание товара должно соответствовать выбранному языку сайта
- Надпись 'Hexlet Store' в шапке сайта должна быть кликабельной и выполнять функцию кнопка 'Главная'
- В бокой части сайта в выпадающем списке 'Категория' должны быть внесены все категории товаров, котороые есть на сайте, а не только те, которые есть на данной странице.
- В бокой части сайта список производителей должен быть помещен в выпадающий список
- В форме фильтрации по цене не должно быть возможности вводить отрицательные числа
- Пользователь не должен иметь возможности вводить специальные символы в формы.
